// <auto-generated />
using System;
using KajBlog_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KajBlog_BackEnd.Migrations
{
    [DbContext(typeof(KajBlogDbContext))]
    [Migration("20241021212420_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KajBlog_BackEnd.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<string>("BlogBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiphyPull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            BlogBody = "C# 10 introduces a number of exciting features, such as global usings and file-scoped namespaces.",
                            Category = "Tech",
                            CreatedBy = "user1",
                            CreatedOn = new DateTime(2024, 10, 21, 21, 24, 19, 963, DateTimeKind.Utc).AddTicks(7928),
                            GiphyPull = "https://giphy.com/some-url",
                            SubjectLine = "Exploring C# 10 Features",
                            UserId = "user1"
                        },
                        new
                        {
                            BlogId = 2,
                            BlogBody = "If you’re looking for the next best travel spots, check out these incredible destinations for 2024.",
                            Category = "Travel",
                            CreatedBy = "user2",
                            CreatedOn = new DateTime(2024, 10, 21, 21, 24, 19, 963, DateTimeKind.Utc).AddTicks(7930),
                            GiphyPull = "https://giphy.com/some-url-2",
                            SubjectLine = "Top 10 Destinations for 2024",
                            UserId = "user2"
                        },
                        new
                        {
                            BlogId = 3,
                            BlogBody = "Mindfulness can help you stay in the present moment and reduce stress. Here's how to get started.",
                            Category = "Health",
                            CreatedBy = "user3",
                            CreatedOn = new DateTime(2024, 10, 21, 21, 24, 19, 963, DateTimeKind.Utc).AddTicks(7931),
                            GiphyPull = "https://giphy.com/some-url-3",
                            SubjectLine = "Mindfulness Techniques for Beginners",
                            UserId = "user3"
                        });
                });

            modelBuilder.Entity("KajBlog_BackEnd.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("KajBlog_BackEnd.Models.Favorite", b =>
                {
                    b.HasOne("KajBlog_BackEnd.Models.Blog", "Blog")
                        .WithMany("Favorites")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("KajBlog_BackEnd.Models.Blog", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
